server {
    server_name music.xedoc.ru;

    root /var/www/music.xedoc.ru/app/frontend/dist;
    index index.html;

    client_max_body_size 512M;

    location ^~ /.well-known/acme-challenge/ {
        root /var/www/_letsencrypt;
        default_type text/plain;
    }

    location = / {
        root /var/www/music.xedoc.ru/app/frontend/dist;
        try_files /simple/index.html =404;
    }

    location = /editor {
        root /var/www/music.xedoc.ru/app/frontend/dist;
        try_files /index.html =404;
    }

    location ^~ /editor/ {
        root /var/www/music.xedoc.ru/app/frontend/dist;
        try_files $uri $uri/ /index.html;
    }

    location = /simple {
        root /var/www/music.xedoc.ru/app/frontend/dist;
        try_files /simple/index.html =404;
    }

    location = /simple/ {
        root /var/www/music.xedoc.ru/app/frontend/dist;
        try_files /simple/index.html =404;
    }

    location ^~ /simple/ {
        root /var/www/music.xedoc.ru/app/frontend/dist;
        try_files $uri /simple/index.html;
    }

    location /api/ {
        proxy_pass http://127.0.0.1:8610;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_read_timeout 3600s;
        proxy_send_timeout 3600s;
        proxy_connect_timeout 10s;
        proxy_buffering off;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }

    listen [::]:443 ssl; # managed by Certbot
    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/music.xedoc.ru/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/music.xedoc.ru/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

}
server {
    if ($host = music.xedoc.ru) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    listen 80;
    listen [::]:80;
    server_name music.xedoc.ru;
    return 404; # managed by Certbot


}